### ISSUE TITLE
Jest appears to cache uninstrumented output and utilize it in coverage runs

### ISSUE THREAD

**Issue by CommanderQ** [salesforce/lwc-test#127]
## Repro Steps
Utilizing the latest release and Jest 26.x or 27.x:
1. Execute a normal Jest unit test run, e.g. `jest`
2. Execute a coverage Jest unit test run, e.g. `jest --coverage`

## Result
Jest will report that tests have passed and that code coverage requirements were "met" / "passing", but does not include any files for code coverage analysis. This leads to an incorrect "passing" state and output such as:

File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   

>Test Suites: 119 passed, 119 total
>Tests:       1332 passed, 1332 total
>Snapshots:   0 total
>Time:        11.483 s

The results vary slightly based upon the execution environment.

### Development Machine
The development machine will consistently report that all tests have passed, but will intermittently execute the code coverage run correctly, including files in the code coverage analysis.

### CI / Jenkins
CI environments consistently manifest this error state and report that all tests have passed and show that the code coverage requirement is vacuously met.

## Workaround
Adding the `--no-cache` option to the coverage command (e.g. `jest coverage --no-cache`) resolves the problem consistently in all environments.

**Comment by pmdartus** [comment]
@CommanderQ Could you share a minimal reproduction repo?
