### ISSUE TITLE
Axe a11y validation error: `(duplicate-id-aria) IDs used in ARIA and labels must be unique`

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc-test#198]
Our snapshots serialize every ID and `aria-*` idref as `[shadow-guid]`:

https://github.com/salesforce/lwc-test/blob/35157d2926c57b287a3bfa77c895733e0a03a9fa/packages/%40lwc/jest-serializer/src/clean-element-attrs.js#L8

This leads to HTML that [Axe](https://www.deque.com/axe/) complains about because of apparent duplicate IDs:

```html
<input type="text" aria-labelledby="[shadow:guid]">
<label id="[shadow:guid]">label1</label>
<input type="text" aria-labelledby="[shadow:guid]">
<label id="[shadow:guid]">label2</label>
```

We should:

1. At the very least, disable this serialization in native shadow
2. Consider another solution so that Axe doesn't complain

**Comment by nolanlawson** [comment]
We should probably do this in such a way that existing snapshots change as little as possible. E.g.

```html
<label id="[shadow:guid]">label1</label>
<label id="[shadow:guid-2]">label2</label>
<label id="[shadow:guid-3]">label3</label>
<!-- etc. -->
```

**Comment by ekashida** [comment]
I think the proposed change would make the serialization completely pointless. If this is the only option, we should just remove it completely.

**Comment by nolanlawson** [comment]
Was the point of https://github.com/salesforce/lwc-test/pull/48 to not have people depend on the exact format of the mangled IDs?

**Comment by ekashida** [comment]
Yeah, we made a change to mangled ids that broke everyone's snapshots so we moved to serializing them in snapshots. That PR you linked to reminded me that we originally stripped it completely. Maybe we should revisit that option.

**Comment by navateja-alagam** [comment]
@ekashida By stripping, do you mean we remove generating `id` attribute altogether in snapshot files. If yes, it may cause accessibility violations to be thrown as for some a11y rules like `aria-labelledby` it looks for corresponding `id` attribute on the DOM.

**Comment by ekashida** [comment]
@navateja-alagam Will it be an issue for axe if every id and every id reference is unique? If so, I think we should be conservative and keep the serialization in place, but append uids that are unique at the snapshot level.

**Comment by nolanlawson** [comment]
@ekashida If we don't modify the IDs/`aria-*`s, and if there are duplicate IDs, then isn't that a true a11y bug at that point?

**Comment by ekashida** [comment]
I meant doing something like the example you showed in [this comment](https://github.com/salesforce/lwc-test/issues/198#issuecomment-1656150973) except to ensure that the uid is reset for each snapshot.

```
<label id="foo">label</label>
<input aria-labelledby="foo">
```
becomes
```
<label id="[shadow:guid-0]">label</label>
<input aria-labelledby="[shadow:guid-1]">
```

**Comment by rui-rayqiu** [comment]
If some a11y rules require that `aria-labelledby` has corresponding `id` attribute in the dom should the example above become
```
<label id="[shadow:guid-0]">label</label>
<input aria-labelledby="[shadow:guid-0]">
```
so that the same ids are transformed into one id?

**Comment by ekashida** [comment]
@rui-rayqiu we could do that, but I was trying to understand how axe works. There are cases where associations are made across shadow boundaries in synthetic shadow so some snapshots would have dangling ids/idrefs. Would these fail?

**Comment by nolanlawson** [comment]
I think aXe supports shadow DOM semantics. AFAICT though this particular test error was coming from sa11y, which I'm pretty sure was just looking at a single component template.
