### ISSUE TITLE
Jest: Support of TypeScript for LWC Open Source

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/lwc-test#35]
When using TypeScript for LWC Open Source projects Jest is failing. This is because of a missing Babel pre-transform step, before the LWC compiler transform the source. 

See the discussion [here](https://github.com/muenzpraeger/create-lwc-app/issues/92#issuecomment-528232156).

**Comment by Templarian** [comment]
@muenzpraeger Did this go out in 1.3?

**Comment by muenzpraeger** [comment]
Yes and no, @templarian.

I am using my own forks till @tbliss publishes an LWC 1.1 build that contains that (now that LWC `latest` is on 1.1).

**Comment by trevor-bliss** [comment]
The PR to consume LWC 1.1 is here: https://github.com/salesforce/lwc-test/pull/26
