### ISSUE TITLE
WDIO: Support of TypeScript for LWC Open Source

### ISSUE THREAD

**Issue by Templarian** [salesforce/lwc-test#37]
Similar to Jest that got updated to support TypeScript we'll need to go through and add the build steps for wdio to run with TypeScript and JS files.

- [ ] Build integration components with TypeScript
- [ ] Allow `__wdio__/*.spec.ts` files
- [ ] Ensure JS works after updates
- [ ] Add `examples/basicts` ?

**Comment by pmdartus** [comment]
Not applicable now that wdio plugin has been removed from this repository: a68aba20c98c433bf9c6e34f5258d9752475b4dd.
