### ISSUE TITLE
wdio: support lwc 1.1.0-beta7

### ISSUE THREAD

**Issue by albert-sf** [salesforce/lwc-test#40]
not compatible with lwc 1.1.0-beta7

**Comment by Templarian** [comment]
Discussed this with @reiniergs this morning.

- [ ] Module resolution updates. We should be getting a document outlining all the changes that went into module resolution for LWC 1.1.

> TS support will come after in #37 and is a lower priority.

**Comment by gonzalocordero** [comment]
@Templarian I want to revive this thread. 

- Do we have specifics about what was not compatible? 
- Is the functionality broken right now? 

Thanks

**Comment by Templarian** [comment]
I'm sure it's broken right now. Now that 1.4 is ready we can update everything to use the latest module resolution I believe. Not sure when I'll have time to look at this next though.

**Comment by gonzalocordero** [comment]
@Templarian I could attempt to look into it, just need to understand the current state, could you elaborate a little bit more? 

Also, I was attempting to do the following:

- I have a sample repo with the base components installed via npm.
- On my jest set up, I map them like so:

```
    moduleNameMapper: {
        '^(my)/(.+)$': '<rootDir>/src/$1/$2/$2',
        '^(lightning)/(.+)$':'<rootDir>/node_modules/lwc-components-lightning/src/$1/$2/$2'
    }
```

However I'm getting an error:

```({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { api, track } from 'lwc';

 SyntaxError: Unexpected token {
```

Is the error related to this issue? what am I missing?

Thanks.

**Comment by Templarian** [comment]
@gonzalocordero That will not work. The `wdio` service code right now was only setup to look in the current project. It's also built using the older version of LWC's module resolution which is not compatible with current version.

We will need to start with a basic hello world app and upgrade the webpack logic to use the new resolution.

Rei's code basically creates the most basic application context to run the wdio tests. This allows the test to run very fast no matter the project size. Ex: 100 component project with 1 wdio test where that component uses 3 other components will only build 4 total components (fixed a ton of bugs around this). The only thing "broken" at the moment is how we resolve those components and their child dependencies.

Make sure you're not using a TS files as I never got TS compilation into the wdio service. I'm assuming it's failing to transpile something right now and hitting a bad token.

**Comment by gonzalocordero** [comment]
I resolved my issue, I was missing the following configuration:

```
    transformIgnorePatterns : ['`/node_modules/(?!${esModules})`'],
```

Also as far as Webpack, Im not sure where that takes part, but we should probably be focusing on rollup instead.

**Comment by Templarian** [comment]
@gonzalocordero I don't know why I typed webpack, that was suppose to say rollup. 🙃

**Comment by pmdartus** [comment]
Not applicable now that wdio plugin has been removed from this repository: a68aba20c98c433bf9c6e34f5258d9752475b4dd.
