### ISSUE TITLE
jest-resolver not resolving lwc modules

### ISSUE THREAD

**Issue by tedconn** [salesforce/lwc-test#45]
The jest resolver invokes the LWC module-resolver. When Jest sees an import, it will compare against the modules returned by the LWC module resolver and then try to return a path to the module.

When the module resolver was refactored in https://github.com/salesforce/lwc/pull/1414 to get rid of implicit, glob-based module resolution, the new module-resolver API is invoked but the rest of the code does not properly support it.

See this line:

https://github.com/salesforce/lwc-test/blob/cc3163e0c67b914295cf326716170b775bd38c53/packages/%40lwc/jest-resolver/src/index.js#L59

This is in the alpha 3.0.0 branch.

**The code is expecting a map but it's getting an array.**

**Comment by ekashida** [comment]
https://github.com/salesforce/lwc-test/pull/58
