### ISSUE TITLE
Remove the out of date example in the wdio-lwc-service package.

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc-test#79]
> remove that example folder (but keep the service itself). The project needs some love and to be updated to support the latest LWC anyway. The example can be added back when that work is done.

https://github.com/salesforce/lwc-test/tree/master/packages/wdio-lwc-service/examples/basic

**Comment by ravijayaramappa** [comment]
@Templarian @gonzalocordero, can you chime in from components perspective and give consent?

**Comment by ravijayaramappa** [comment]
cc @reiniergs

**Comment by Templarian** [comment]
@ravijayaramappa Yes removing that is fine. The example in the future can be kept elsewhere also.

**Comment by pmdartus** [comment]
Fixed with a68aba20c98c433bf9c6e34f5258d9752475b4dd.
