### ISSUE TITLE
@lwc/synthetic-shadow installed even when native Shadow DOM is available

### ISSUE THREAD

**Issue by aputinski** [salesforce/lwc-test#93]
Looks like this check is returning `undefined` even when native Shadow DOM is available (JSDOM 16).

https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-preset/src/setup.js#L9

I'm guessing `$constructorCache$` was changed at some point in JSDOM.

Our LWC components are used with native Shadow DOM, so we have a few tests that check things like `assignedNodes()`

**Comment by pmdartus** [comment]
Shadow DOM has been introduced in jsdom 2 years ago with the [12.2 release](https://github.com/jsdom/jsdom/releases/tag/12.2.0). JSDOM 16.0 adds support for custom elements. So far synthetic shadow was always enabled regardless if native shadow DOM was supported on not by jsdom. Based on this, I don't think the `$constructorCache$` is linked to your issue.

@aputinski Could you please share a minimal repro of your issue for us to investigate further?

Note: As of jsdom 16, the DOM constructors and prototypes are recreated from scratch. This `$constructorCache$` is not needed anymore.

**Comment by aputinski** [comment]
> So far synthetic shadow was always enabled regardless if native shadow DOM was supported on not by jsdom.

`@lwc/synthetic-shadow` seems to be conditionally required based on that check?

Here's the test case:
https://github.com/aputinski/lwc-jest-preset-test-case

**Comment by pmdartus** [comment]
I gave a look into this specific issue and I understand better the source of this issue. `@lwc/jest-preset` always enables the synthetic shadow today to match what is currently experience in Lightning. Currently, LWC component using the synthetic shadow doesn't support slotting for the top-level component. This is why `assignedNodes()` doesn't return the right result in the test.

IMO, we should add a config flag to turn off synthetic shadow in the case where it is not needed.
